//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaiteHallintaSovellus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asennukset
    {
        public int AsennusID { get; set; }
        public int Ohjelma_ID { get; set; }
        public int Laite_ID { get; set; }
    
        public virtual Laitteet Laitteet { get; set; }
        public virtual Ohjelmat Ohjelmat { get; set; }
    }
}
