//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaiteHallintaSovellus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Laiterekisteri_dbEntities : DbContext
    {
        public Laiterekisteri_dbEntities()
            : base("name=Laiterekisteri_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Asennukset> Asennukset { get; set; }
        public virtual DbSet<Laitteet> Laitteet { get; set; }
        public virtual DbSet<Ohjelmat> Ohjelmat { get; set; }
        public virtual DbSet<Sijainnit> Sijainnit { get; set; }
        public virtual DbSet<Varastot> Varastot { get; set; }
    }
}
