//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaiteHallintaSovellus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sijainnit
    {
        public int Sijainti_ID { get; set; }
        public int Varasto_ID { get; set; }
        public int Laite_ID { get; set; }
        public System.DateTime Pvm { get; set; }
    
        public virtual Laitteet Laitteet { get; set; }
        public virtual Varastot Varastot { get; set; }
    }
}
