//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaiteHallintaSovellus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laitteet
    {
        public int Laite_ID { get; set; }
        public string Tyyppi { get; set; }
        public string Malli { get; set; }
        public string Valmistaja { get; set; }
        public string Kuvaus { get; set; }
        public string Sarjanumero { get; set; }
        public System.DateTime Hankinta_Pvm { get; set; }
        public Nullable<int> Takuu_Aika { get; set; }
        public string QR_Koodi { get; set; }
    }
}
