//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaiteHallintaSovellus
{
    using System;
    using System.Collections.Generic;
    
    public partial class Varastot
    {
        public int Varasto_ID { get; set; }
        public string Varasto { get; set; }
        public string Osoite { get; set; }
        public int Postinro { get; set; }
        public string Postitoimipaikka { get; set; }
        public Nullable<int> Kerros { get; set; }
        public Nullable<int> Kone_Maara { get; set; }
        public Nullable<int> Henkilo_Maara { get; set; }
        public Nullable<int> Neliot { get; set; }
        public string QR_Koodi { get; set; }
    }
}
